spring:
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/content/   # .html 파일을 불러오기 위한 경로 설정(src/main/resources/templates)
    suffix: .html   # 파일 확장자
    cache: false
    mode: HTML
  mvc:
    static-path-pattern: /resources/static/** # spring mvc 정적경로 변경
  devtools:
    livereload:
      enabled: true
  datasource:
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@127.0.0.1:1521:XE
#    username: hwang
#    password: rootoor
#    driver-class-name: org.mariadb.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/mysql
    username: root
    password: root
  # data:
  #   elasticsearch:
  #     cluster-nodes: localhost:9300
  #     cluster-name: my-cluster
  profiles:
    include: oauth

elasticsearch:
  port: 9300
  host: localhost
  clustername: hwang-cluster

server:
  port: 8050

mybatis:
  mapper-locations: classpath:mappers/*.xml

api:
  culture:
    key: e4cad89f-ee3b-4062-b13e-60734d47a93c

thread:
  pool:
    size: 2

